version: '3.9'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - eshopnet
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: wurstmeister/kafka
    networks:
      - eshopnet
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:1:1,catalog:1:1,basket:1:1"

  postgres:
    build: postgres
    networks:
      - eshopnet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser

  redis:
    image: redis:6.2.4
    networks:
      - eshopnet
    ports:
      - "6379:6379"
    restart: on-failure
    environment:
      REDIS_PASSWORD: pass

networks:
  eshopnet:
    driver: bridge