version: '3.5'

services:
    zookeeper:
      image: wurstmeister/zookeeper

    kafka:
      image: wurstmeister/kafka
      depends_on:
        - zookeeper
      links:
        - zookeeper
      ports:
        - 9092:9092
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "order:1:1,catalog:1:1"

    postgres:
      build: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: dbpass
        POSTGRES_USER: dbuser
